# Welcome to the Python course for beginners

These notebooks should give you a basic introduction to the Python world, and should help you understand why people keep talking about snakes and pandas.

Eoghan O'Connell, Guck Division, MPL, 2021

In [23]:
# notebook metadata you can ignore!
info = {"tutorial": "basic-numpy",
        "version" : "0.0.1"}

### How to use this notebook

- Click on a cell (each box is called a cell). hit "shift+enter"
- You can run the cells in any order!
- The output of runnable code is printed below the cell.
- Check out the Jupyter Notebook Tutorial video in the repo.

See the help tab above for more information!


-------------
# NumPy arrays introduction
#### What is in this notebook?
In this tutorial we cover:
- What is NumPy
- What is a NumPy array
- How to index and slice numpy arrays
- When to use numpy arrays

-------
## What is NumPy

- NumPy stands for Numerical Python.
- It is a core scientific package and you will probably use it a lot.
- It's easy and fast.
- We will use numpy arrays for images, storing numbers etc.
- It is not internal to python, so we have to import it!

In [1]:
import numpy as np

# now we can use all the functions of numpy by calling `np`

print(np)

# look, it's just in a folder in the computer! All of the python pckages will be in a "site-packages" folder

<module 'numpy' from 'c:\\users\\eoconne\\miniconda3\\lib\\site-packages\\numpy\\__init__.py'>


-------
## Numpy arrays
Let's make a basic numpy array

In [3]:
# np.zeros will give you an array of zeros of the shape given
np.zeros(3)

# you can see that the output looks like a list

array([0., 0., 0.])

In [5]:
# np.ones gives you ones instead

np.ones(3)

array([1., 1., 1.])

What if we want a 2-dimensional array? Just change the shape.

The x axis is always the last axis in numpy

In [7]:
np.zeros((2, 3))

# this ouputs a 2 * 3 array (y*x)

array([[0., 0., 0.],
       [0., 0., 0.]])

What if we want a 3- or 4-dimensional array? Just change the shape!

In [8]:
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# 4 dimensions:

np.zeros((3, 2, 2, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

#### We can make numpy arrays from other python objects like lists and numbers

In [17]:
list_of_numbers = [2, 3, 4, 8, 10] 
arr1 = np.array(list_of_numbers)  # just turns list into an array just like that!

print(arr1)

[ 2  3  4  8 10]


In [18]:
#indexing

arr1[0]

2

In [19]:
# slicing

arr1[0:3]

array([2, 3, 4])

It looks similar to a list, but can do lots of extra cool stuff very quickly

In [20]:
# multiplying lists (fails)
list_of_numbers * list_of_numbers

TypeError: can't multiply sequence by non-int of type 'list'

In [21]:
# multiplying arrays is no problem
arr1 * arr1

array([  4,   9,  16,  64, 100])

In [22]:
# multiplying a list with an array works
arr1 * list_of_numbers

array([  4,   9,  16,  64, 100])

In [27]:
# what about with single numbers?
arr1 * 8.33

array([16.66, 24.99, 33.32, 66.64, 83.3 ])

In [28]:
# using boolean
arr1 * False

# numpy is excellent at working with boolean masks. Check out "np.where"

array([0, 0, 0, 0, 0])

----------
## Fancy indexing
Numpy has a fancy indexing notation for slicing and indexing nulti-dimensional arrays.

Let's make a 2D numpy array and start slicing:

In [33]:
arr2 = np.array([[2, 3, 4, 5],
                 [9, 5, 1, 2],
                 [3, 4, 7, 1]])
print(arr2)

[[2 3 4 5]
 [9 5 1 2]
 [3 4 7 1]]


In [34]:
arr2[0:2, 1:3]

# here we grab the y axis values from the 0th to 2nd index, and the x axis values from 1st to 3rd index
# we are basically just cropping the array by grabbing a 2D slice

array([[3, 4],
       [5, 1]])

## When to use each data type

- lists (`list`): use when you want to gather objects together. Use it for strings, numbers, lists, dicts etc.
- (numpy) arrays (`np.array`): use when you are dealing with numbers/boolean values, want speed, looking at image data